from typing import List, Optional
from openenv.core.env_server.types import Action, Observation
from pydantic import Field

class GamemasterAction(Action):
    """Action for the Gamemaster Env environment - what the GM says and does."""
    narrative_response: str = Field(..., description="The narrative story told to the player.")
    target_to_damage: Optional[str] = Field(None, description="Name of character/monster to apply damage to (e.g., 'goblin').")
    damage_amount: int = Field(0, description="Amount of damage to apply.")
    item_to_give: Optional[str] = Field(None, description="Item to give to the player (e.g., 'gold coin').")

class GamemasterObservation(Observation):
    """Observation from the Gamemaster Env environment - the true world state and player input."""
    player_input: str = Field(..., description="What the player wants to do.")
    system_dice_roll: int = Field(..., description="The result of a d20 roll generated by the game engine.")
    player_hp: int = Field(..., description="Player's current HP.")
    goblin_hp: int = Field(..., description="Goblin's current HP.")
    inventory: List[str] = Field(..., description="Player's current inventory.")
    engine_feedback: str = Field(default="", description="Feedback from the engine on the GM's previous action.")
