from typing import List, Optional, Dict
from openenv.core.env_server.types import Action, Observation
from pydantic import Field

class GamemasterAction(Action):
    """Action for the Gamemaster Env environment - what the GM says and does."""
    gm_logic: str = Field(..., description="System 2 Chain-of-Thought: Explain your reasoning for the mechanics and narrative based on the dice roll and rules.")
    narrative_response: str = Field(..., description="The narrative story told to the player.")
    target_to_damage: Optional[str] = Field(None, description="Name of character/monster to apply damage to.")
    damage_amount: int = Field(0, description="Amount of damage to apply.")
    item_to_give: Optional[str] = Field(None, description="Item to give to the party (e.g., 'gold coin').")
    next_monster_name: Optional[str] = Field(None, description="If advancing level, generate the next monster's name.")
    next_monster_hp: Optional[int] = Field(None, description="If advancing level, set the next monster's max HP.")
    next_monster_dmg: Optional[int] = Field(None, description="If advancing level, set the next monster's attack damage.")

class GamemasterObservation(Observation):
    """Observation from the Gamemaster Env environment - the true world state and player input."""
    active_player: str = Field(..., description="The name of the player taking the turn.")
    player_input: str = Field(..., description="What the active player wants to do.")
    system_dice_roll: int = Field(..., description="The result of a d20 roll generated by the game engine.")
    party_hp: Dict[str, int] = Field(..., description="Current HP of all 4 party members (Fighter, Rogue, Wizard, Cleric).")
    monster_name: str = Field(..., description="Current monster's name.")
    monster_hp: int = Field(..., description="Monster's current HP.")
    inventory: List[str] = Field(..., description="Party's shared inventory.")
    engine_feedback: str = Field(default="", description="Feedback from the engine on the GM's previous action.")
